"""adiciona campo ativo ao instrutor

Revision ID: 13fcfff3915e
Revises: 907200a90c9c
Create Date: 2026-09-08 20:26:08.467243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fcfff3915e'
down_revision = '907200a90c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
