"""recriando após mudanças

Revision ID: 17fa6e019f07
Revises: 
Create Date: 2025-11-23 15:26:32.142578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fa6e019f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracao_dias', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ficha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.String(length=20), nullable=False),
    sa.Column('carga', sa.String(length=20), nullable=True),
    sa.Column('descanso', sa.String(length=20), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['ficha_id'], ['ficha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treino')
    op.drop_table('ficha')
    op.drop_table('alunos')
    op.drop_table('planos')
    op.drop_table('instrutores')
    op.drop_table('exercicio')
    # ### end Alembic commands ###
