"""cria tabela de pagamentos

Revision ID: 74c21aa0a5d7
Revises: 13fcfff3915e
Create Date: 2026-10-03 22:41:07.309137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c21aa0a5d7'
down_revision = '13fcfff3915e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_pagamentos_aluno_id_alunos')),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], name=op.f('fk_pagamentos_instrutor_id_instrutores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    # ### end Alembic commands ###
