"""empty message

Revision ID: 75027569e099
Revises: c11af9aa3263
Create Date: 2025-11-16 12:23:13.606193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75027569e099'
down_revision = 'c11af9aa3263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercicio')
    # ### end Alembic commands ###
