"""empty message

Revision ID: 75d908e9e947
Revises: f456ba924031
Create Date: 2025-12-06 12:25:42.080376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d908e9e947'
down_revision = 'f456ba924031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treino_exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.String(length=50), nullable=False),
    sa.Column('carga', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_semana', sa.String(length=20), nullable=True))
        batch_op.drop_column('repeticoes')
        batch_op.drop_column('ordem')
        batch_op.drop_column('exercicio_id')
        batch_op.drop_column('series')
        batch_op.drop_column('descanso')
        batch_op.drop_column('carga')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('carga', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('descanso', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('series', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('exercicio_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('ordem', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('repeticoes', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'exercicio', ['exercicio_id'], ['id'])
        batch_op.drop_column('dia_semana')

    op.drop_table('treino_exercicio')
    # ### end Alembic commands ###
