"""adiciona instrutor_id em aluno e plano

Revision ID: 907200a90c9c
Revises: 75d908e9e947
Create Date: 2026-09-07 11:34:11.802657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907200a90c9c'
down_revision = '75d908e9e947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrutor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_alunos_instrutor_id_instrutores'), 'instrutores', ['instrutor_id'], ['id'])

    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrutor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_planos_instrutor_id_instrutores'), 'instrutores', ['instrutor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_planos_instrutor_id_instrutores'), type_='foreignkey')
        batch_op.drop_column('instrutor_id')

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alunos_instrutor_id_instrutores'), type_='foreignkey')
        batch_op.drop_column('instrutor_id')

    # ### end Alembic commands ###