"""empty message

Revision ID: f456ba924031
Revises: 17fa6e019f07
Create Date: 2025-11-23 20:03:15.006345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f456ba924031'
down_revision = '17fa6e019f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.alter_column('repeticoes',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.TEXT(), nullable=True))
        batch_op.alter_column('repeticoes',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
